acoustic_model_path: /Users/laurettacheng/Documents/MFA/pretrained_models/acoustic/english.zip
begin: 1617852410.480891
corpus_directory: /Users/laurettacheng/Documents/UM/UM_Research/anANAs/GUAva/corpus/aligned_audio/cali-kr/original_corpus/AMYLEE
dictionary_path: /Users/laurettacheng/Documents/MFA/pretrained_models/dictionary/english.dict
dirty: false
type: align
version: 2.0.0a5
