acoustic_model_path: /Users/laurettacheng/Documents/MFA/pretrained_models/acoustic/english.zip
begin: 1617851573.215005
corpus_directory: "/Users/laurettacheng/Documents/UM/UM_Research/anANAs/GUAva/corpus/aligned_audio/cali-tw/original_corpus/CynthiaHuang\u9EC3\
  \u99A8\u5100"
dictionary_path: /Users/laurettacheng/Documents/MFA/pretrained_models/dictionary/english.dict
dirty: false
type: align
version: 2.0.0a5
